### ISSUE TITLE
Allowing user extension of imports

### ISSUE THREAD

**Issue by scottkidder** [sukima/vim-ember-imports#11]
I've tried to add some of my own frequently used imports by adding something like this to my .vimrc

```
call extend(g:vim_ember_import_definitions, {
	\   'setupMirage': {'default': v:true, 'from': 'ember-cli-mirage/test-support/setup-mirage'},
	\ })
```

but it seems the variable is not accessible to me:

```
E121: Undefined variable: g:vim_ember_import_definitions
E116: Invalid arguments for function extend
```

Am I doing something wrong here or do we need to add a new variable to allow the plugin to merge in the user defined imports?

Also it may be interesting to enable some kind of plugin system where plugins could add project specific imports. I'm thinking ember-data could be split out, along with new plugins for mirage, ember-intl, and others.

**Comment by sukima** [comment]
Confirmed, this is a bug. I’m away from my computer for a few days. Will set a eminent to folllow up on a fix. Sorry ’bout that.

I will also concider the plug in thing if I can growk how to do that.

**Comment by sukima** [comment]
@scottkidder I have completely redone this plugin. I moved all the logic to another plugin called [vim-javascript-imports][1] and this one just adds the ember definitions.

The [vim-javascript-imports][1] plugin adds an API for adding your own definitions. In your case you could do the following in your `vimrc`:

```vim
JSAdd import setupMirage from ember-cli-mirage/test-support/setup-mirage
```

[1]: https://github.com/sukima/vim-javascript-imports

**Comment by scottkidder** [comment]
@sukima :clap: Nicely done!
