### ISSUE TITLE
ENH: Add import-sort

### ISSUE THREAD

**Issue by scottkidder** [sukima/vim-ember-imports#2]
Just leaving this here as an idea to automatically sort imports. I use https://github.com/renke/import-sort and https://github.com/ruanyl/vim-sort-imports which follows the ESlint sort-imports rule.

**Comment by sukima** [comment]
The plugin already sorts a single import as follows:

1. default
2. each destructured variable sorted alphabetically

As for the import lines themselves I think every project would have a different sorting wouldn't they?

Maybe a check if `exists('*:SortImports')` and call it after an insertion?

**Comment by scottkidder** [comment]
https://github.com/renke/import-sort is flexible and has several different configurations available or anyone can create their own.

**Comment by scottkidder** [comment]
closed by #6
